#!/usr/bin/env python3
# Copyright (c) 2026 Beijing Volcano Engine Technology Co., Ltd.
# SPDX-License-Identifier: MIT
"""gen_tfvars.py — Translate a lightweight Volcengine deploy choice/context
file into terraform.tfvars consumed by the IaC root module.

Usage:
    gen_tfvars.py --input <deploy-choice.json> --output <terraform.tfvars>
                  [--project <name>] [--region <code>]

Mapping summary:
  * mode/deploy_mode + dependencies decide which modules are enabled
  * estimated load → instance type and node count
    using a coarse lookup table (kept intentionally small; the operator can
    override any value before running `terraform apply`).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


# Coarse-grained sizing table. Keys are "deploy_mode + workload size";
# value is the recommended VKE node instance type (ECS spec name).
NODE_INSTANCE_TYPE_TABLE = {
    "vke_light": "ecs.g3i.large",
    "vke_standard": "ecs.g3i.xlarge",
    "vke_heavy": "ecs.g3i.2xlarge",
}

# RDS MySQL spec mapping by workload tier.
RDS_SPEC_TABLE = {
    "light": "rds.mysql.1c2g",
    "standard": "rds.mysql.2c4g",
    "heavy": "rds.mysql.4c8g",
}

# Redis shard capacity (MiB) by tier.
REDIS_SHARD_CAPACITY_TABLE = {
    "light": 1024,
    "standard": 4096,
    "heavy": 8192,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate terraform.tfvars from deploy choice/context JSON")
    parser.add_argument("--input", required=True, help="Path to .volcengine/deploy-choice.json or equivalent context JSON")
    parser.add_argument("--output", required=True, help="Path to write terraform.tfvars")
    parser.add_argument("--project", help="Override project name (default: derived from repo_name)")
    parser.add_argument("--region", help="Override region (default: derived from identity.region)")
    parser.add_argument("--workload", default="standard", choices=["light", "standard", "heavy"],
                        help="Workload tier; affects instance sizing")
    return parser.parse_args()


def hcl_string(value: str) -> str:
    """Quote a string for HCL, escaping double quotes and backslashes."""
    escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
    return f"\"{escaped}\""


def hcl_list(items: list[str]) -> str:
    return "[" + ", ".join(hcl_string(x) for x in items) + "]"


def hcl_bool(value: bool) -> str:
    return "true" if value else "false"


def derive_az_pair(region: str) -> tuple[str, str]:
    """Return (primary_az, secondary_az) defaults for a region.
    Uses the convention <region>-a / <region>-b which matches Volcengine's pattern."""
    return (f"{region}-a", f"{region}-b")


def write_tfvars(report: dict[str, Any], out_path: Path, project: str, region: str, workload: str) -> None:
    deploy_mode = report.get("mode") or report.get("deploy_mode", "vke")
    deps: list[str] = report.get("dependencies") or report.get("repo_analysis", {}).get("dependencies", []) or []
    primary_az, secondary_az = derive_az_pair(region)

    enable_vke = deploy_mode == "vke"
    enable_rds = "mysql" in deps or "postgresql" in deps
    enable_redis = "redis" in deps
    enable_tos = "tos" in deps or "s3-compatible" in deps
    # CR is needed whenever VKE is in play (image push target). Keep it standalone too
    # so users can drive a separate FaaS-with-container path later without rewiring.
    enable_cr = enable_vke

    lines: list[str] = []
    lines.append(f"# Generated by gen_tfvars.py from deploy choice/context JSON")
    lines.append(f"# project: {project}  region: {region}  deploy_mode: {deploy_mode}  workload: {workload}")
    lines.append("")
    lines.append(f"project = {hcl_string(project)}")
    lines.append(f"region  = {hcl_string(region)}")
    lines.append(f"az_primary   = {hcl_string(primary_az)}")
    lines.append(f"az_secondary = {hcl_string(secondary_az)}")
    lines.append("")
    lines.append(f"enable_vke   = {hcl_bool(enable_vke)}")
    lines.append(f"enable_cr    = {hcl_bool(enable_cr)}")
    lines.append(f"enable_rds   = {hcl_bool(enable_rds)}")
    lines.append(f"enable_redis = {hcl_bool(enable_redis)}")
    lines.append(f"enable_tos   = {hcl_bool(enable_tos)}")
    lines.append("")

    if enable_vke:
        node_type = NODE_INSTANCE_TYPE_TABLE[f"vke_{workload}"]
        lines.append(f"node_instance_type      = {hcl_string(node_type)}")
        lines.append(f"node_count_desired      = {2 if workload == 'light' else (3 if workload == 'standard' else 5)}")
        lines.append(f"node_count_min          = 1")
        lines.append(f"node_count_max          = {5 if workload != 'heavy' else 10}")
        lines.append("")

    if enable_rds:
        lines.append(f"rds_instance_type = {hcl_string(RDS_SPEC_TABLE[workload])}")
        lines.append(f"rds_storage_space = {100 if workload != 'heavy' else 500}")
        lines.append("")

    if enable_redis:
        lines.append(f"redis_shard_capacity = {REDIS_SHARD_CAPACITY_TABLE[workload]}")
        lines.append(f"redis_node_number    = {2 if workload != 'light' else 1}")
        lines.append("")

    if enable_tos:
        bucket_name = f"{project}-app-{region}".lower().replace("_", "-")
        lines.append(f"tos_bucket_name = {hcl_string(bucket_name)}")
        lines.append("")

    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    args = parse_args()
    in_path = Path(args.input)
    if not in_path.exists():
        print(f"Error: input file not found: {in_path}", file=sys.stderr)
        return 1

    try:
        report = json.loads(in_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"Error: invalid JSON in {in_path}: {exc}", file=sys.stderr)
        return 1

    project = args.project or report.get("project") or report.get("repo_name") or "myapp"
    region = args.region or report.get("region") or report.get("identity", {}).get("region") or os.environ.get("VOLCENGINE_REGION", "cn-beijing")

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_tfvars(report, out_path, project, region, args.workload)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
